version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 963982835422.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=963982835422.dkr.ecr.us-east-1.amazonaws.com/node-hello
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker-compose -f docker-compose.yml build
      - docker-compose push
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker-compose -f docker-compose.yml push
artifacts:
  files: imagedefinitions.json