version: '3.3'
services:
  redis:
    restart: on-failure
    build: ./redis
    image: "963982835422.dkr.ecr.us-east-1.amazonaws.com/node-hello"
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web1
    image: "963982835422.dkr.ecr.us-east-1.amazonaws.com/redis"
    ports:
      - '3000:3000'

