version: '3.3'
services:
  redis:
    restart: on-failure
    build: ./redis
    image: "${REPOSITORY_URI}/redis:${IMAGE_TAG}"
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web1
    image: "${REPOSITORY_URI}/node-hello:${IMAGE_TAG}"
    ports:
      - '3000:3000'

